# Expected Variables
# TAG - Tag or version of the containers
version: '2'
services:
  controller:
    image: contrail-controller-liberty:${TAG}
    privileged: true
    network_mode: host
    pid: "host"
    cap_add:
      - AUDIT_WRITE
    environment:
      - CLOUD_ORCHESTRATOR=kubernetes
  analytics:
    image: contrail-analytics-liberty:${TAG}
    privileged: true
    network_mode: host
    pid: "host"
    cap_add:
      - AUDIT_WRITE
    depends_on:
     - controller
    environment:
      - CLOUD_ORCHESTRATOR=kubernetes
